### ISSUE TITLE
For a void method force return does not work

### ISSUE THREAD

**Issue by Vampire** [lppedd/idea-debugger-enhancer#3]
If you want to force return from a void method, it does not work.
You have either to select "Value" or "Exception".
Choosing "Value" and entering "null" did not work at least due to #4.
Choosing "Value" and entering an empty string, shows a dialog that an empty string is not compatible to `void`.
Only "Exception" option is usable for a `void` method currently.

**Comment by Vampire** [comment]
It might even be two issues.
When I configure `null` just nothing happens, but `idea.log` shows.
```
java.lang.NullPointerException
        at com.github.lppedd.debugger.EnhancedLineBreakpoint.returnValue(EnhancedLineBreakpoint.kt:110)
        at com.github.lppedd.debugger.EnhancedLineBreakpoint.threadAction(EnhancedLineBreakpoint.kt:99)
        at com.github.lppedd.debugger.EnhancedLineBreakpoint.processLocatableEvent(EnhancedLineBreakpoint.kt:51)
        at com.intellij.debugger.engine.DebugProcessEvents$2.contextAction(DebugProcessEvents.java:609)
        at com.intellij.debugger.engine.events.SuspendContextCommandImpl.action(SuspendContextCommandImpl.java:59)
        at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:43)
        at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:155)
        at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:30)
        at com.intellij.debugger.impl.InvokeThread.lambda$run$0(InvokeThread.java:138)
        at com.intellij.openapi.project.DumbService.runWithAlternativeResolveEnabled(DumbService.java:383)
        at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:125)
        at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.lambda$run$0(InvokeThread.java:49)
        at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
        at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:48)
        at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:263)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

If I instead try to return an empty string, a dialog is shown that tells me that a string is not compatible with `void`.
