### ISSUE TITLE
Version 0.1 stopped working with IntelliJ IDEA 2022.1.1

### ISSUE THREAD

**Issue by JThoennes** [lppedd/idea-debugger-enhancer#5]
The plugin stopped working with the newest IDE version:
- IDE Internal Errors (stacktrace.txt):
```
java.lang.AbstractMethodError: Receiver class com.github.lppedd.debugger.EnhancedDebuggerApplicationLoadListener does not define or inherit an implementation of the resolved method 'abstract void beforeApplicationLoaded(com.intellij.openapi.application.Application, java.nio.file.Path)' of interface com.intellij.ide.ApplicationLoadListener.
	at com.intellij.idea.ApplicationLoader.initConfigurationStore(ApplicationLoader.kt:422)
	at com.intellij.idea.ApplicationLoader$initApplication$block$3.apply(ApplicationLoader.kt:137)
	at com.intellij.idea.ApplicationLoader$initApplication$block$3.apply(ApplicationLoader.kt)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at com.intellij.idea.ApplicationLoader$initApplication$block$2.execute(ApplicationLoader.kt:123)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1069)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
- Version
```
IntelliJ IDEA 2022.1.1 (Ultimate Edition)
Build #IU-221.5591.52, built on May 10, 2022
Licensed to Jörg Thönnes
Subscription is active until June 3, 2022.
Runtime version: 11.0.14.1+1-b2043.45 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.10.0-13-amd64
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Non-Bundled Plugins:
    pw.unbear.ijplug (1.0.0)
    org.nik.presentation-assistant (1.0.9)
    org.jetbrains.search-everywhere-docs (1.0.12)
    org.intellij.RegexpTester (1.0.8)
    net.seesharpsoft.intellij.plugins.csv (2.18.2)
    krasa.CpuUsageIndicator (1.14)
    indent-rainbow.indent-rainbow (2.0.2)
    com.jetbrains.edu (2022.4-2022.1-218)
    com.intellij.ideolog (203.0.29.0)
    org.jetbrains.plugins.hocon (2022.1.0)
    org.jetbrains.jumpToLine (0.1.8)
    com.tang (1.3.6.251-IDEA213)
    com.github.lppedd.idea-debugger-enhancer (0.1)
    com.github.b3er.idea.plugins.arc.browser (0.32)
    com.genuitec.codetogether (2022.1.4-01289)
    com.dubreuia (2.3.0)
    com.databricks (1.1)
    org.antlr.jetbrains.st4plugin (0.9)
    VisualVMLauncher (1.21.211.6085.0)
    String Manipulation (9.4.0)
    Key Promoter X (2022.1.2)
    JOL (1.10.0)
    GrepConsole (12.12.211.6693.0)
    zielu.gittoolbox (212.8.9)
    org.sonarlint.idea (6.7.0.45926)
    me.artspb.hackathon.git.bisect.run (0.7.4)
    FitNesse (1.13.0)
    com.intellij.kubernetes (221.5591.58)
    DBN (3.3.1779.0)
    com.yiycf.plugins.mavenDependencyHelper (2.5)
    MavenRunHelper (4.20.213.3714.1)
    org.intellij.scala (2022.1.14)
    Pythonid (221.5591.52)
    com.intellij.bigdatatools (221.4165.63)
    com.haulmont.jpab (2022.2.2-221)
    SequenceDiagram (2.1.8)

Kotlin: 221-1.6.21-release-337-IJ5591.52
Current Desktop: XFCE
```

**Comment by Vampire** [comment]
This also causes IntelliJ to show two possible "Line Breakpoints" to set.
At least the second option vanishes if this plugin gets deactivated.
